# cookstyle (rubocop) todo:

Lint/UselessAssignment:
  Exclude:
    - 'providers/ark.rb'

Style/AccessorMethodName:
  Exclude:
    - 'libraries/matchers.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'libraries/helpers.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'providers/ark.rb'
