knife client delete mindtree-elasticsearch-acceptance-0 -y
knife client delete mindtree-elasticsearch-production-0 -y
knife client delete mindtree-jenkins-management-0 -y
knife client delete mindtree-jfrog-management-0 -y
knife client delete mindtree-maven-management-0 -y
knife client delete mindtree-mysql-acceptance-0 -y
knife client delete mindtree-mysql-production-0 -y
knife client delete mindtree-redis-acceptance-0 -y
knife client delete mindtree-redis-production-0 -y
knife client delete mindtree-sensu-management-0 -y
knife client delete mindtree-splunk-management-0 -y
knife client delete mindtree-tomcat-acceptance-0 -y
knife client delete mindtree-tomcat-acceptance-1 -y
knife client delete mindtree-tomcat-production-0 -y
knife client delete mindtree-tomcat-production-1 -y
knife node delete mindtree-elasticsearch-acceptance-0 -y
knife node delete mindtree-elasticsearch-production-0 -y
knife node delete mindtree-jenkins-management-0 -y
knife node delete mindtree-jfrog-management-0 -y
knife node delete mindtree-maven-management-0 -y
knife node delete mindtree-mysql-acceptance-0 -y
knife node delete mindtree-mysql-production-0 -y
knife node delete mindtree-redis-acceptance-0 -y
knife node delete mindtree-redis-production-0 -y
knife node delete mindtree-sensu-management-0 -y
knife node delete mindtree-splunk-management-0 -y
knife node delete mindtree-tomcat-acceptance-0 -y
knife node delete mindtree-tomcat-production-0 -y
knife node delete mindtree-tomcat-production-1 -y
knife node delete mindtree-tomcat-acceptance-1 -y
