LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

SpaceBeforeFirstArg:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
