---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    uchiwa:
      api: [
        {
          name: sensu1,
          host: api1.example.com,
          port: 4567,
          ssl: false,
          timeout: 5000
        },
        {
          name: sensu2,
          host: api2.example.com,
          port: 4567,
          ssl: false,
          timeout: 5000
        }
      ]

platforms:
  - name: centos-6.5
  - name: centos-7.0
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: repo
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: repo

  - name: http
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: http
        version: 0.12.0-1

  - name: disabled_service
    excludes:
      - centos-7.0
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: repo
        manage_service: false

  - name: package_options_ubuntu_http
    excludes:
      - centos-6.5
      - centos-7.0
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: http
        version: 0.12.0-1
        package_options: --log=/tmp/uchiwa_pkg.log

  - name: package_options_ubuntu_repo
    excludes:
      - centos-6.5
      - centos-7.0
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: repo
        package_options: -o Dpkg::Options::="--log=/tmp/uchiwa_pkg.log"

  - name: package_options_centos_http
    excludes:
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: http
        version: 0.12.0-1
        package_options: --nogpgcheck > /tmp/uchiwa_pkg.log

  - name: package_options_centos_repo
    excludes:
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        install_method: repo
        package_options: --nogpgcheck > /tmp/uchiwa_pkg.log
